/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cliente;

/**
 *
 * @author alvar
 */
public class FrmCliente extends javax.swing.JFrame {

    /**
     * Creates new form FrmCliente
     */
    Cliente cliente;

    public FrmCliente() {
        initComponents();
        cliente = new Cliente(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl1Negro = new javax.swing.JButton();
        lbl1rojo = new javax.swing.JButton();
        lbl1azul = new javax.swing.JButton();
        lbl2negro = new javax.swing.JButton();
        lbl2rojo = new javax.swing.JButton();
        lbl2azul = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPuerto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl1Negro.setBackground(new java.awt.Color(0, 0, 0));
        lbl1Negro.setForeground(new java.awt.Color(255, 255, 255));
        lbl1Negro.setText("NEGRO");
        lbl1Negro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl1NegroActionPerformed(evt);
            }
        });

        lbl1rojo.setBackground(new java.awt.Color(204, 0, 0));
        lbl1rojo.setForeground(new java.awt.Color(255, 255, 255));
        lbl1rojo.setText("ROJO");
        lbl1rojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl1rojoActionPerformed(evt);
            }
        });

        lbl1azul.setBackground(new java.awt.Color(0, 0, 204));
        lbl1azul.setForeground(new java.awt.Color(255, 255, 255));
        lbl1azul.setText("AZUL");
        lbl1azul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl1azulActionPerformed(evt);
            }
        });

        lbl2negro.setBackground(new java.awt.Color(0, 0, 0));
        lbl2negro.setForeground(new java.awt.Color(255, 255, 255));
        lbl2negro.setText("NEGRO");
        lbl2negro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl2negroActionPerformed(evt);
            }
        });

        lbl2rojo.setBackground(new java.awt.Color(204, 0, 0));
        lbl2rojo.setForeground(new java.awt.Color(255, 255, 255));
        lbl2rojo.setText("ROJO");
        lbl2rojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl2rojoActionPerformed(evt);
            }
        });

        lbl2azul.setBackground(new java.awt.Color(0, 0, 255));
        lbl2azul.setForeground(new java.awt.Color(255, 255, 255));
        lbl2azul.setText("AZUL");
        lbl2azul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl2azulActionPerformed(evt);
            }
        });

        jLabel1.setText("BOMBA 1");

        jLabel2.setText("BOMBA 2");

        jLabel3.setText("IP");

        jLabel4.setText("PUERTO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(lbl1Negro, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl1rojo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl1azul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(lbl2negro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl2rojo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl2azul)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(92, 92, 92))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIp, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPuerto)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1Negro)
                    .addComponent(lbl1rojo)
                    .addComponent(lbl1azul)
                    .addComponent(lbl2negro)
                    .addComponent(lbl2rojo)
                    .addComponent(lbl2azul))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl1NegroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl1NegroActionPerformed
        // TODO add your handling code here:
        cliente.enviarMensaje("negro1", Integer.parseInt(txtPuerto.getText()), txtIp.getText());
    }//GEN-LAST:event_lbl1NegroActionPerformed

    private void lbl1rojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl1rojoActionPerformed
        // TODO add your handling code here:
        cliente.enviarMensaje("rojo1", Integer.parseInt(txtPuerto.getText()), txtIp.getText());

    }//GEN-LAST:event_lbl1rojoActionPerformed

    private void lbl1azulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl1azulActionPerformed
        cliente.enviarMensaje("azul1", Integer.parseInt(txtPuerto.getText()), txtIp.getText());

    }//GEN-LAST:event_lbl1azulActionPerformed

    private void lbl2negroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl2negroActionPerformed
        cliente.enviarMensaje("negro2", Integer.parseInt(txtPuerto.getText()), txtIp.getText());

    }//GEN-LAST:event_lbl2negroActionPerformed

    private void lbl2rojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl2rojoActionPerformed
        // TODO add your handling code here:
        cliente.enviarMensaje("rojo2", Integer.parseInt(txtPuerto.getText()), txtIp.getText());

    }//GEN-LAST:event_lbl2rojoActionPerformed

    private void lbl2azulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl2azulActionPerformed
        // TODO add your handling code here:
        cliente.enviarMensaje("azul2", Integer.parseInt(txtPuerto.getText()), txtIp.getText());

    }//GEN-LAST:event_lbl2azulActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton lbl1Negro;
    private javax.swing.JButton lbl1azul;
    private javax.swing.JButton lbl1rojo;
    private javax.swing.JButton lbl2azul;
    private javax.swing.JButton lbl2negro;
    private javax.swing.JButton lbl2rojo;
    private javax.swing.JTextField txtIp;
    private javax.swing.JTextField txtPuerto;
    // End of variables declaration//GEN-END:variables
}
